# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://doyu.github.io/hello_nbdev/"

git_url = "https://github.com/doyu/hello_nbdev/tree/main/"

def custom_doc_links(name): return None
